baseURL = "http://fedepaol.github.io/"
languageCode = "en-us"
title = "My little software warehouse"
theme = "charaka-hugo-theme"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[permalinks]
  posts = "/blog/:year/:month/:day/:title/"


[params]
  author = "Federico Paolinelli"
  # Description/subtitle for homepage (can be Markdown)
  description = "Random ramblings on software development"



[[params.social]]
  url = "https://twitter.com/fedepaol"
  fa_icon = "fab fa-twitter"

[params.highlight]
  style = "zenburn"

[[params.social]]
  url = "about"
  fa_icon = "fas fa-info" 

[[params.social]]
  url = "https://github.com/fedepaol"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "www.linkedin.com/in/federico-paolinelli-2374954/"
  fa_icon = "fab fa-linkedin-in"

